apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: emsi-ebank-discovery-service
  name: emsi-ebank-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emsi-ebank-discovery-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/komp-default: "true"
        io.kompose.service: emsi-ebank-discovery-service
    spec:
      containers:
        - image: emsi-ebank-discovery-service
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health
            failureThreshold: 4
            periodSeconds: 10
          name: emsi-ebank-discovery-service
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
      restartPolicy: Always
