apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: emsi-gateway-service
  name: emsi-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emsi-gateway-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/komp-default: "true"
        io.kompose.service: emsi-gateway-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_URL
              value: http://emsi-ebank-config-service:9999
            - name: DISCOVERY_SERVICE_URL
              value: http://emsi-ebank-discovery-service:8761/eureka
          image: emsi-gateway-service
          name: emsi-gateway-service
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
      restartPolicy: Always
