apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: emsi-ebank-discovery-service
  name: emsi-ebank-discovery-service
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
    - name: 8761-tcp
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: emsi-ebank-discovery-service
