@Library('shared-libraries') _

commonPipeline(
    repoUrl: 'https://github.com/YassineElabdaoui/devops_microservices.git',
    branch: 'main',
    serviceDir: 'discovery-service',
    dockerImage: 'yassine2023/devops-discovery-service',
    dockerCredentialsId: 'dockerhub-pwd',
    dockerUsername: 'yassine2023'
)